### ISSUE TITLE
raw @alert tag

### ISSUE THREAD

**Issue by abrca** [WildGums/WildGums.OpenSource#2]
There are raw "@alert important / @end" tags on the html pages at the https://opensource.wildgums.com site:

\orc.dynamicobjects
\orc.entityframework (+ subpages)
\orc.prism (+ subpages)
\orc.skia

like:
![image](https://user-images.githubusercontent.com/20093250/80987233-2c96e780-8e4b-11ea-95f2-778ceaaaa309.png)

**Comment by Orcomp** [comment]
Thanks. Fixed
