### ISSUE TITLE
wrong markup

### ISSUE THREAD

**Issue by abrca** [WildGums/WildGums.OpenSource#3]
There is wrong markup - unnecessary ` (grave accent) in Nuget Packages section in two files:

\src\content\orc.search\_index.md
\src\content\orc.squirrel\_index.md

![image](https://user-images.githubusercontent.com/20093250/81034990-736bf800-8eb2-11ea-8de7-bf842071f978.png)

**Comment by Orcomp** [comment]
Thanks for reporting.

@GeertvanHorrik I am fixing this now

**Comment by Orcomp** [comment]
Fixed. Pushed
