### ISSUE TITLE
broken badges

### ISSUE THREAD

**Issue by abrca** [WildGums/WildGums.OpenSource#4]
Broken badges in \src\content\orc.csvhelper\_index.md

![image](https://user-images.githubusercontent.com/20093250/81035295-cdb98880-8eb3-11ea-9ee5-587ef205ff3e.png)

Package was renamed to orc.csv

**Comment by GeertvanHorrik** [comment]
The folder needs renaming too.

**Comment by Orcomp** [comment]
Done
